.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. dollar_qt test_dollar_qt
clean: FORCE
	$(MAKE) -C .. dollar_qt_clean test_dollar_qt_clean
check: FORCE
	$(MAKE) -C .. test_dollar_qt_check
dollar-qt dollar-qt.exe: FORCE
	 $(MAKE) -C .. dollar_qt
